// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-onion-arch-sample/ent/predicate"
	"go-onion-arch-sample/ent/profile"
	"go-onion-arch-sample/ent/task"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProfileUpdate is the builder for updating Profile entities.
type ProfileUpdate struct {
	config
	hooks    []Hook
	mutation *ProfileMutation
}

// Where appends a list predicates to the ProfileUpdate builder.
func (pu *ProfileUpdate) Where(ps ...predicate.Profile) *ProfileUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetName sets the "name" field.
func (pu *ProfileUpdate) SetName(s string) *ProfileUpdate {
	pu.mutation.SetName(s)
	return pu
}

// SetEmail sets the "email" field.
func (pu *ProfileUpdate) SetEmail(s string) *ProfileUpdate {
	pu.mutation.SetEmail(s)
	return pu
}

// SetPhotoURL sets the "photo_url" field.
func (pu *ProfileUpdate) SetPhotoURL(s string) *ProfileUpdate {
	pu.mutation.SetPhotoURL(s)
	return pu
}

// SetNillablePhotoURL sets the "photo_url" field if the given value is not nil.
func (pu *ProfileUpdate) SetNillablePhotoURL(s *string) *ProfileUpdate {
	if s != nil {
		pu.SetPhotoURL(*s)
	}
	return pu
}

// ClearPhotoURL clears the value of the "photo_url" field.
func (pu *ProfileUpdate) ClearPhotoURL() *ProfileUpdate {
	pu.mutation.ClearPhotoURL()
	return pu
}

// SetUpdateAt sets the "update_at" field.
func (pu *ProfileUpdate) SetUpdateAt(t time.Time) *ProfileUpdate {
	pu.mutation.SetUpdateAt(t)
	return pu
}

// SetDeleteAt sets the "delete_at" field.
func (pu *ProfileUpdate) SetDeleteAt(t time.Time) *ProfileUpdate {
	pu.mutation.SetDeleteAt(t)
	return pu
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (pu *ProfileUpdate) SetNillableDeleteAt(t *time.Time) *ProfileUpdate {
	if t != nil {
		pu.SetDeleteAt(*t)
	}
	return pu
}

// ClearDeleteAt clears the value of the "delete_at" field.
func (pu *ProfileUpdate) ClearDeleteAt() *ProfileUpdate {
	pu.mutation.ClearDeleteAt()
	return pu
}

// AddTaskIDs adds the "Tasks" edge to the Task entity by IDs.
func (pu *ProfileUpdate) AddTaskIDs(ids ...int) *ProfileUpdate {
	pu.mutation.AddTaskIDs(ids...)
	return pu
}

// AddTasks adds the "Tasks" edges to the Task entity.
func (pu *ProfileUpdate) AddTasks(t ...*Task) *ProfileUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return pu.AddTaskIDs(ids...)
}

// Mutation returns the ProfileMutation object of the builder.
func (pu *ProfileUpdate) Mutation() *ProfileMutation {
	return pu.mutation
}

// ClearTasks clears all "Tasks" edges to the Task entity.
func (pu *ProfileUpdate) ClearTasks() *ProfileUpdate {
	pu.mutation.ClearTasks()
	return pu
}

// RemoveTaskIDs removes the "Tasks" edge to Task entities by IDs.
func (pu *ProfileUpdate) RemoveTaskIDs(ids ...int) *ProfileUpdate {
	pu.mutation.RemoveTaskIDs(ids...)
	return pu
}

// RemoveTasks removes "Tasks" edges to Task entities.
func (pu *ProfileUpdate) RemoveTasks(t ...*Task) *ProfileUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return pu.RemoveTaskIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProfileUpdate) Save(ctx context.Context) (int, error) {
	pu.defaults()
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProfileUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProfileUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *ProfileUpdate) defaults() {
	if _, ok := pu.mutation.UpdateAt(); !ok {
		v := profile.UpdateDefaultUpdateAt()
		pu.mutation.SetUpdateAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *ProfileUpdate) check() error {
	if v, ok := pu.mutation.Name(); ok {
		if err := profile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Profile.name": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Email(); ok {
		if err := profile.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Profile.email": %w`, err)}
		}
	}
	return nil
}

func (pu *ProfileUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(profile.Table, profile.Columns, sqlgraph.NewFieldSpec(profile.FieldID, field.TypeString))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Name(); ok {
		_spec.SetField(profile.FieldName, field.TypeString, value)
	}
	if value, ok := pu.mutation.Email(); ok {
		_spec.SetField(profile.FieldEmail, field.TypeString, value)
	}
	if value, ok := pu.mutation.PhotoURL(); ok {
		_spec.SetField(profile.FieldPhotoURL, field.TypeString, value)
	}
	if pu.mutation.PhotoURLCleared() {
		_spec.ClearField(profile.FieldPhotoURL, field.TypeString)
	}
	if value, ok := pu.mutation.UpdateAt(); ok {
		_spec.SetField(profile.FieldUpdateAt, field.TypeTime, value)
	}
	if value, ok := pu.mutation.DeleteAt(); ok {
		_spec.SetField(profile.FieldDeleteAt, field.TypeTime, value)
	}
	if pu.mutation.DeleteAtCleared() {
		_spec.ClearField(profile.FieldDeleteAt, field.TypeTime)
	}
	if pu.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profile.TasksTable,
			Columns: []string{profile.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedTasksIDs(); len(nodes) > 0 && !pu.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profile.TasksTable,
			Columns: []string{profile.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profile.TasksTable,
			Columns: []string{profile.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// ProfileUpdateOne is the builder for updating a single Profile entity.
type ProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProfileMutation
}

// SetName sets the "name" field.
func (puo *ProfileUpdateOne) SetName(s string) *ProfileUpdateOne {
	puo.mutation.SetName(s)
	return puo
}

// SetEmail sets the "email" field.
func (puo *ProfileUpdateOne) SetEmail(s string) *ProfileUpdateOne {
	puo.mutation.SetEmail(s)
	return puo
}

// SetPhotoURL sets the "photo_url" field.
func (puo *ProfileUpdateOne) SetPhotoURL(s string) *ProfileUpdateOne {
	puo.mutation.SetPhotoURL(s)
	return puo
}

// SetNillablePhotoURL sets the "photo_url" field if the given value is not nil.
func (puo *ProfileUpdateOne) SetNillablePhotoURL(s *string) *ProfileUpdateOne {
	if s != nil {
		puo.SetPhotoURL(*s)
	}
	return puo
}

// ClearPhotoURL clears the value of the "photo_url" field.
func (puo *ProfileUpdateOne) ClearPhotoURL() *ProfileUpdateOne {
	puo.mutation.ClearPhotoURL()
	return puo
}

// SetUpdateAt sets the "update_at" field.
func (puo *ProfileUpdateOne) SetUpdateAt(t time.Time) *ProfileUpdateOne {
	puo.mutation.SetUpdateAt(t)
	return puo
}

// SetDeleteAt sets the "delete_at" field.
func (puo *ProfileUpdateOne) SetDeleteAt(t time.Time) *ProfileUpdateOne {
	puo.mutation.SetDeleteAt(t)
	return puo
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (puo *ProfileUpdateOne) SetNillableDeleteAt(t *time.Time) *ProfileUpdateOne {
	if t != nil {
		puo.SetDeleteAt(*t)
	}
	return puo
}

// ClearDeleteAt clears the value of the "delete_at" field.
func (puo *ProfileUpdateOne) ClearDeleteAt() *ProfileUpdateOne {
	puo.mutation.ClearDeleteAt()
	return puo
}

// AddTaskIDs adds the "Tasks" edge to the Task entity by IDs.
func (puo *ProfileUpdateOne) AddTaskIDs(ids ...int) *ProfileUpdateOne {
	puo.mutation.AddTaskIDs(ids...)
	return puo
}

// AddTasks adds the "Tasks" edges to the Task entity.
func (puo *ProfileUpdateOne) AddTasks(t ...*Task) *ProfileUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return puo.AddTaskIDs(ids...)
}

// Mutation returns the ProfileMutation object of the builder.
func (puo *ProfileUpdateOne) Mutation() *ProfileMutation {
	return puo.mutation
}

// ClearTasks clears all "Tasks" edges to the Task entity.
func (puo *ProfileUpdateOne) ClearTasks() *ProfileUpdateOne {
	puo.mutation.ClearTasks()
	return puo
}

// RemoveTaskIDs removes the "Tasks" edge to Task entities by IDs.
func (puo *ProfileUpdateOne) RemoveTaskIDs(ids ...int) *ProfileUpdateOne {
	puo.mutation.RemoveTaskIDs(ids...)
	return puo
}

// RemoveTasks removes "Tasks" edges to Task entities.
func (puo *ProfileUpdateOne) RemoveTasks(t ...*Task) *ProfileUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return puo.RemoveTaskIDs(ids...)
}

// Where appends a list predicates to the ProfileUpdate builder.
func (puo *ProfileUpdateOne) Where(ps ...predicate.Profile) *ProfileUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProfileUpdateOne) Select(field string, fields ...string) *ProfileUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Profile entity.
func (puo *ProfileUpdateOne) Save(ctx context.Context) (*Profile, error) {
	puo.defaults()
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProfileUpdateOne) SaveX(ctx context.Context) *Profile {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProfileUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *ProfileUpdateOne) defaults() {
	if _, ok := puo.mutation.UpdateAt(); !ok {
		v := profile.UpdateDefaultUpdateAt()
		puo.mutation.SetUpdateAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *ProfileUpdateOne) check() error {
	if v, ok := puo.mutation.Name(); ok {
		if err := profile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Profile.name": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Email(); ok {
		if err := profile.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Profile.email": %w`, err)}
		}
	}
	return nil
}

func (puo *ProfileUpdateOne) sqlSave(ctx context.Context) (_node *Profile, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(profile.Table, profile.Columns, sqlgraph.NewFieldSpec(profile.FieldID, field.TypeString))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Profile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, profile.FieldID)
		for _, f := range fields {
			if !profile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != profile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Name(); ok {
		_spec.SetField(profile.FieldName, field.TypeString, value)
	}
	if value, ok := puo.mutation.Email(); ok {
		_spec.SetField(profile.FieldEmail, field.TypeString, value)
	}
	if value, ok := puo.mutation.PhotoURL(); ok {
		_spec.SetField(profile.FieldPhotoURL, field.TypeString, value)
	}
	if puo.mutation.PhotoURLCleared() {
		_spec.ClearField(profile.FieldPhotoURL, field.TypeString)
	}
	if value, ok := puo.mutation.UpdateAt(); ok {
		_spec.SetField(profile.FieldUpdateAt, field.TypeTime, value)
	}
	if value, ok := puo.mutation.DeleteAt(); ok {
		_spec.SetField(profile.FieldDeleteAt, field.TypeTime, value)
	}
	if puo.mutation.DeleteAtCleared() {
		_spec.ClearField(profile.FieldDeleteAt, field.TypeTime)
	}
	if puo.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profile.TasksTable,
			Columns: []string{profile.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedTasksIDs(); len(nodes) > 0 && !puo.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profile.TasksTable,
			Columns: []string{profile.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   profile.TasksTable,
			Columns: []string{profile.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Profile{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
