// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Profile is the predicate function for profile builders.
type Profile func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)
